name: signify_quotes_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  get_it: ^7.7.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  path: ^1.9.0
  dartz: ^0.10.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
